version: "3.9"

services:
  apache:
      image: php:7.4-apache
      volumes:
        - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
      ports:
        - "3001:80"
      depends_on:
        - api
      networks:
        - healthconnect_net

  api:
    depends_on:
      - db #je dépends de la base de donnée
    build:
      context: .
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
    container_name: healthconnect_app
    networks:
      - healthconnect_net

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthconnect
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - healthconnect_net

  # Ce connecter à la db du docker
  # docker exec -it idConteneur bash
  # mysql -u user -ppassword healthconnect

networks:
  healthconnect_net:
    driver: bridge

volumes:
  db_data:
