name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - connectVPS
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: healthconnect
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql

      - name: Install dependencies
        run: |
          composer install --no-cache --no-ansi --no-interaction --no-progress --no-suggest --optimize-autoloader

      - name: Make PHPUnit executable
        run: chmod +x vendor/bin/phpunit
  
      - name: Run backend tests
        run: vendor/bin/phpunit

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/HealthConnect/healthconnect-backend
            git pull
            docker build -t healthconnect-backend:${{ github.sha }} .
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 8080:80 healthconnect-backend:${{ github.sha }}
