name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Pipeline
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: healthconnect
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: pdo_mysql

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      - name: Run backend tests
        run: |
          # Here you would run your tests, for example:
          echo "Running PHP tests"
          # Assuming you have PHPUnit or any other test suite configured
          # ./vendor/bin/phpunit tests

      - name: Build and push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t Wickeur/healthconnect-backend .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push Wickeur/healthconnect-backend